### ISSUE TITLE
feature request - which door or lock?

### ISSUE THREAD

**Issue by Trblz42** [desertblade/Keymaster-Basic#15]
The current code refers to "unlocked the ???? door at" but I would like to know **which door** was unlocked.
How can we know which door was opened?

```
choose:
  - conditions:
      - condition: template
        value_template: >
          {% set mysensor = "input_boolean.lock_code_slot_" ~ unlock_code_slot ~
          "_notify" %}  

          {{is_state(mysensor, 'on') }}
    sequence:
      - action: notify.lock_notify_group
        data:
          message: >-
            {% set namesensor = "input_text.lock_code_slot_" ~ unlock_code_slot
            ~ "_name" %} {{ states(namesensor)}} unlocked the ???? door at {{
            now().strftime('%H:%M') }}
```

**Comment by desertblade** [comment]
Added what lock is being unlocked in the message.  If it doesn't work let me know. I had notifications turned off on this repo for some reason, they should be back on.

```YAML
      - service: notify.lock_notify_group
        data:
          message: >-
            {% set namesensor = "input_text.lock_code_slot_" ~ unlock_code_slot ~ "_name" %} 
            {{ states(namesensor)}} unlocked the {{ device_name(trigger.event.data.device_id) }} at
            {{ now().strftime('%H:%M') }}
```
