### ISSUE TITLE
Invalid config for [notify.group]: invalid slug

### ISSUE THREAD

**Issue by Trblz42** [desertblade/Keymaster-Basic#5]
if i follow the guide, i am getting an "Invalid config for [notify.group]: invalid slug" message. 

resolved this by updating keymaster_basic.yaml from

```
notify:
  - name: "Lock Notify Group"
    platform: group
    services:
      - service: notify.mobile_app_<deviceid>
```

to

```
notify:
  - name: "Lock Notify Group"
    platform: group
    services:
      - service: mobile_app_<deviceid>
```
