### ISSUE TITLE
Changes not sent to ZWave device

### ISSUE THREAD

**Issue by Trblz42** [desertblade/Keymaster-Basic#6]
I am using a ZWaveJS UI combination with Yale Zwave locks.

When i set a PIN/Username, i am not seeing messages sent out.

My setup is the following: 

/config/configuration.yaml

```
..
# Keymaster
homeassistant:
  packages: !include_dir_named packages
..
```

/config/packages/keymaster_basic.yaml

```
..
# Add your locks here
lock:
  - platform: group
    name: "House Locks"
    entities:
      - lock.FrontDoor
      - lock.GarageDoor
      - lock.OfficeDoor

# Add notification services
notify:
  - name: "Lock Notify Group"
    platform: group
    services:
      - service: mobile_app_DEVICE
..
```

**Comment by Trblz42** [comment]
ok, so i keep learning.

the problem was that my entity names did not reflect the entity IDs. The change to below made the code work.

```
# Add your locks here
lock:
  - platform: group
    name: "House Locks"
    entities:
      - lock.node_12 #FrontDoor
      - lock.assure_lever_keypad_with_z_wave_plus #GarageDoor
      - lock.assure_touchscreen_deadbolt #OfficeDoor
```
