### ISSUE TITLE
Notifications not all logging / working

### ISSUE THREAD

**Issue by Trblz42** [desertblade/Keymaster-Basic#7]
i have two common users of my locks
UserA on PIN1
UserB on PIN2
for both the notifications are enabled

when i look at my HA notifications on my phone, i see
Executed: October 30, 2023 at 06:20:26
    message: UserA unlocked the door via keypad at 21:20:04
Executed: October 29, 2023 at 21:20:04
    message: UserA unlocked the door via keypad at 21:20:04
Executed: October 29, 2023 at 16:26:28
    message: UserB unlocked the door via keypad at 16:26:28

UserA gets notifications but with a recurring timestamp.
Overall, UserA and UserB use the keypad more than the number of entries in the logbook.

**Comment by Mattheinrichs** [comment]
Had the same problem - seems like the last_changed value isn't getting updated? as you show, it seems to "stick".
I updated my script to use now() instead:

              - service: notify.lock_notify_group
                data:
                  message: >-
                    {% set namesensor = "input_text.lock_code_slot_" ~
                    states('input_text.last_lock_unlock_code_slot') ~ "_name" %} {{
                    states(namesensor)}} unlocked the door at
                    {{ now().strftime('%H:%M') }}

**Comment by desertblade** [comment]
@ Trblz42 
I was finally was able to spend some time and reworked notifications.  I ditched last changed, it wasn't working for me and felt clunky. Used Trigger Variables to get the userID.  

Here is the new notify automation:
```
 - alias: Lock Notifications
    description: "Notify when certain codes are used to unlock the doors, if notify is enabled"
    id: lock_notifications
    trigger:
      - platform: event
        event_type: zwave_js_notification
        event_data:
          command_class: 113
          command_class_name: Notification
          label: Access Control
          type: 6
          event: 6
          event_label: Keypad unlock operation
        variables:
          unlock_code_slot: "{{ trigger.event.data.parameters.userId }}"
    condition: []
    action:
      - choose:
          - conditions:
              - condition: template
                value_template: |
                  {% set mysensor = "input_boolean.lock_code_slot_" ~ unlock_code_slot ~ "_notify" %}  
                  {{is_state(mysensor, 'on') }}
            sequence:
              - service: notify.lock_notify_group
                data:
                  message: >-
                    {% set namesensor = "input_text.lock_code_slot_" ~
                    unlock_code_slot ~ "_name" %} {{
                    states(namesensor)}} unlocked the door at
                    {{ now().strftime('%H:%M') }}
    mode: single
    ```
    
    Updated the package content.
