### ISSUE TITLE
Different service for notifications possible?

### ISSUE THREAD

**Issue by lrgabriel** [desertblade/Keymaster-Basic#9]
Hello!

I am switching to a different notifications platform...I was wondering if it's possible for Keymaster-basic to support [ntfy](https://ntfy.sh/).  I'm not sharp enough to be able to modify the .yaml myself...I was hoping to ask for your help!

[Here's the page](https://docs.ntfy.sh/examples/#home-assistant) from Ntfy for supporting Home Assistant.  Specifically, there's this section:

```
notify:
  - name: ntfy
    platform: rest
    method: POST_JSON
    data:
      topic: YOUR_NTFY_TOPIC
    title_param_name: title
    message_param_name: message
    resource: https://ntfy.sh
```

Thank you for taking the time to look at this.  Please let me know if I can do any testing or anything to help.

**Comment by desertblade** [comment]
It should be notify agnostic. Once you setup a notify service you can add it in notify group.  I am assuming that ntfy is using the standard notification setup for home assistant. https://www.home-assistant.io/integrations/notify/

**Comment by lrgabriel** [comment]
I finally got this working!  

1. I installed this as a HACS integration: [hbrennhaeuser/homeassistant_integration_ntfy](https://github.com/hbrennhaeuser/homeassistant_integration_ntfy)

2. I added this to my `homeassistant/configuration.yaml`:
```
notify:
    - name: ntfy_notification
      platform: ntfy
      topic: '<insert your topic name here>'
      url: 'https://ntfy.sh' 
      allow_topic_override: True 
```
3. My `/homeassistant/packages/keymaster_basic.yaml` has this near the top of the file:
```
# Add notification services
notify:
  - platform: group
    name: "Lock Notify Group"
    services:
      - service: ntfy_notification
```
